// app/layout.js (Global layout - applied to public routes)
import "../../globals.css";
import Sidebar from "@/Component/sidebar";



export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=" antialiased font-serif`}"
      >
        <div className="flex gap-3 antialiased font-serif">
          <Sidebar /> {/* This is your global header */}
          {children} {/* Render children for all public routes */}
        </div>

      </body>
    </html>
  );
}
