// app/layout.js (Global layout - applied to public routes)
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import PublicHeader from "@/Component/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-serif`}
      >
        <PublicHeader /> {/* This is your global header */}
          {children}
        {/* Render children for all public routes */}
      </body>
    </html>
  );
}
